### PR TITLE
Return tests results

### LINKED ISSUE #3: Return test results rather than nil
Hi James,

I'm interested in using eftest during CI, which would mean I need to know if tests have failed. With that information I can exit with a non-zero status etc.

Would you be open to returning a map that describes the test run rather than `nil` in order to make this possible?

### PR DESCRIPTION
**Pull request by jcf**
Hey James,

Hope this finds you well.

I was hoping to add some tests but it's tricky testing the tests, as I'm sure you're aware. I thought about adding a nested Leiningen project and shelling out to make sure we do the right thing, but with the progress bar and additional complexity…

This PR returns the hash-map of test summary info so we can programmatically do things. The commit below describes what's going on. Oh, and I snuck a small documentation fix in that I thought you'd be cool with. If you'd prefer it in a separate PR please cherry pick it out.

All the best old friend,

Other James

---

Previously running tests via `eftest.runner/run-tests` would return `nil` making
it impossible to know if we have a green/red build. This change returns a map of
information similar to that of clojure.test itself (with an additional
`:duration` key-value pair that describes how long our tests took to run).

This change makes it possible to use eftest's `run-tests` programmatically,
which allows us to use eftest in CI and other systems where we may need to
forward the success or failure of a given test run to some external system.

The return value of a test run now looks something like this:

    {:duration 12, :error 0, :fail 1, :pass 0, :test 1, :type :summary}

This new return value means you can something like this:

    (let [{:keys [error fail]} (-> "test"
                                    eftest.runner/find-tests
                                    eftest.runner/run-tests)]
      (when-not (and (zero? error) (zero? fail))
        (System/exit (Math/max 255 (+ (:error m) (:fail m)))))

Note the use of `Math/max`. You can't use a status code larger than 255!

Fixes #3.

### CODE REVIEW

File: src/eftest/runner.clj [hunk 1]
```diff
@@ -84,10 +84,14 @@
   ([vars opts]
    (let [start-time (System/currentTimeMillis)]
      (if (empty? vars)
-       (println "No tests found.")
+       (do
+         (println "No tests found.")
+         test/*initial-report-counters*)
```
Comment (jcf) [inline src/eftest/runner.clj]: I didn't want to hardcode this value in case someone else knew better (in his/her application). I figured the dynamic default in clojure.test made the most semantic sense here.

File: src/eftest/runner.clj [hunk 2]
```diff
@@ -84,10 +84,14 @@
...
        (binding [report/*context* (atom {})
                  test/report      (:report opts progress/report)]
          (test/do-report {:type :begin-test-run, :count (count vars)})
          (let [counters (test-all vars opts)
-               duration (- (System/currentTimeMillis) start-time)]
-           (test/do-report (assoc counters :type :summary, :duration duration))))))))
+               duration (- (System/currentTimeMillis) start-time)
```
Comment (jcf) [inline src/eftest/runner.clj]: This is entirely pedantic, but I wonder if use of `(System/nanoTime)` makes sense here… on the off chance that NTP kicks in and a clock skews. Not a change for this PR, but maybe something to change in #5?

Comment (weavejester) [inline src/eftest/runner.clj]: This seems like a good idea.

File: src/eftest/runner.clj (hunk 1 above)
Comment (weavejester) [inline src/eftest/runner.clj]: That's fine.

**Comment by weavejester** [comment]
Thanks! It looks good. I think we can shorten the commit message on the third commit, however. Something like:

```
Change run-tests to return a summary map

The summary map contains keys for :duration, :error, :fail, :pass and
:test. This makes it possible to programmatically determine whether a
test run succeeded or failed.
```

File: src/eftest/runner.clj [hunk 3]
```diff
@@ -84,10 +84,14 @@
...
+               summary (assoc counters :type :summary, :duration duration)]
```
Comment (weavejester) [inline src/eftest/runner.clj]: Why `:type :summary`?

Comment (jcf) [inline src/eftest/runner.clj]: I didn't add `:type :summary`, and it appears that's what [`clojure.test` does too](https://github.com/clojure/clojure/blob/2e0c0a9a89ede8221504edeb90e8c4ee6cce7e16/src/clj/clojure/test.clj#L767-L777).

Do you want to `dissoc` the `:type` before returning the map?

**Comment by jcf** [comment]
I've changed the commit message to your terser version.

File: src/eftest/runner.clj (hunk 2 above)
Comment (jcf) [inline src/eftest/runner.clj]: See #5.

File: src/eftest/runner.clj (hunk 3 above)
Comment (weavejester) [inline src/eftest/runner.clj]: Hm, I guess adding an additional key couldn't hurt if it retains compatibility. It seems a little superfluous, though when used as a return value rather than with `do-report`. I guess keep it for now.
